SECTOR_MAP = {
    "AAPL": "Mega Cap Tech",
    "MSFT": "Mega Cap Tech",
    "GOOGL": "Mega Cap Tech",
    "META": "Mega Cap Tech",
    "AMZN": "Mega Cap Tech",
    "NFLX": "Mega Cap Tech",
    "TSLA": "EV / Consumer Tech",

    "NVDA": "Semiconductors",
    "AMD": "Semiconductors",
    "AVGO": "Semiconductors",
    "MU": "Semiconductors",
    "ARM": "Semiconductors",
    "TSM": "Semiconductors",
    "QCOM": "Semiconductors",
    "INTC": "Semiconductors",
    "SMCI": "Semiconductors",
    "MRVL": "Semiconductors",
    "ON": "Semiconductors",
    "MPWR": "Semiconductors",
    "KLAC": "Semiconductors",
    "LRCX": "Semiconductors",
    "AMAT": "Semiconductors",
    "ADI": "Semiconductors",
    "NXPI": "Semiconductors",

    "CDNS": "Semiconductor Software",
    "SNPS": "Semiconductor Software",

    "PLTR": "AI / Data",
    "AI": "AI / Data",
    "BBAI": "AI / Data",
    "SOUN": "AI / Data",
    "TEM": "AI / Healthcare",
    "PATH": "Automation / AI",

    "SNOW": "Cloud Software",
    "DDOG": "Cloud Software",
    "NET": "Cloud Software",
    "MDB": "Cloud Software",
    "ESTC": "Cloud Software",
    "DOCN": "Cloud Software",
    "CRM": "Cloud Software",
    "NOW": "Cloud Software",
    "ORCL": "Cloud Software",
    "SAP": "Cloud Software",

    "ADBE": "Software",
    "INTU": "Software",
    "WDAY": "Software",
    "GTLB": "Software",
    "ASAN": "Software",
    "TWLO": "Software",

    "OKTA": "Cybersecurity",
    "CRWD": "Cybersecurity",
    "PANW": "Cybersecurity",
    "ZS": "Cybersecurity",
    "S": "Cybersecurity",

    "SHOP": "E-Commerce",
    "SHOP.TO": "Canada / Tech",
    "UBER": "Consumer Platforms",
    "ABNB": "Consumer Platforms",
    "RBLX": "Gaming / Metaverse",
    "SE": "International Tech",
    "ROKU": "Streaming / Ads",
    "DUOL": "Consumer Apps",
    "APP": "Ad Tech",
    "TTD": "Ad Tech",
    "PINS": "Social Media",
    "SPOT": "Streaming",
    "HIMS": "Consumer Health",
    "CELH": "Consumer Staples Growth",

    "HOOD": "Fintech / Crypto",
    "SOFI": "Fintech",
    "COIN": "Crypto",
    "MSTR": "Crypto",

    "RKLB": "Space",
    "LUNR": "Space",
    "ASTS": "Space",
    "ACHR": "Aviation / eVTOL",
    "JOBY": "Aviation / eVTOL",

    "LMT": "Defense",
    "RTX": "Defense",
    "NOC": "Defense",
    "GD": "Defense",
    "HII": "Defense",
    "KTOS": "Defense",
    "BA": "Aerospace",

    "GE": "Industrials",
    "GEV": "Energy Infrastructure",
    "CAT": "Industrials",
    "DE": "Industrials",
    "ETN": "Industrials",
    "PH": "Industrials",
    "HON": "Industrials",
    "MMM": "Industrials",
    "UPS": "Transports",
    "FDX": "Transports",
    "UNP": "Transports",
    "CSX": "Transports",

    "JPM": "Financials",
    "GS": "Financials",
    "MS": "Financials",
    "BAC": "Financials",
    "WFC": "Financials",
    "BLK": "Financials",
    "SCHW": "Financials",
    "KKR": "Financials",
    "BX": "Financials",
    "V": "Payments",
    "MA": "Payments",
    "AXP": "Payments",
    "COF": "Financials",
    "C": "Financials",
    "USB": "Financials",
    "PNC": "Financials",

    "LLY": "Healthcare",
    "NVO": "Healthcare",
    "UNH": "Healthcare",
    "ISRG": "Healthcare",
    "VRTX": "Healthcare",
    "ABBV": "Healthcare",
    "MRK": "Healthcare",
    "PFE": "Healthcare",
    "TMO": "Healthcare",
    "DHR": "Healthcare",
    "BSX": "Healthcare",
    "SYK": "Healthcare",
    "MDT": "Healthcare",
    "ABT": "Healthcare",
    "AMGN": "Healthcare",
    "GILD": "Healthcare",

    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "SLB": "Energy",
    "HAL": "Energy",
    "EOG": "Energy",
    "OXY": "Energy",
    "MPC": "Energy",
    "PSX": "Energy",
    "VLO": "Energy",
    "LNG": "Energy",
    "WMB": "Energy",
    "KMI": "Energy",

    "COST": "Consumer Defensive",
    "WMT": "Consumer Defensive",
    "TGT": "Consumer Defensive",
    "HD": "Consumer Cyclical",
    "LOW": "Consumer Cyclical",
    "SBUX": "Consumer Cyclical",
    "MCD": "Consumer Defensive",
    "CMG": "Consumer Cyclical",
    "NKE": "Consumer Cyclical",
    "TJX": "Consumer Cyclical",
    "BKNG": "Travel",
    "MAR": "Travel",
    "DIS": "Entertainment",
    "LULU": "Consumer Cyclical",
    "EL": "Consumer Defensive",

    "FCX": "Materials",
    "NEM": "Gold / Materials",
    "LIN": "Materials",
    "APD": "Materials",
    "MLM": "Materials",
    "VMC": "Materials",
    "NUE": "Steel",
    "STLD": "Steel",
    "AA": "Aluminum",
    "MOS": "Agriculture / Materials",

    "NEE": "Utilities",
    "SO": "Utilities",
    "DUK": "Utilities",
    "AEP": "Utilities",
    "XEL": "Utilities",
    "CEG": "Utilities / Nuclear",
    "PEG": "Utilities",
    "SRE": "Utilities",

    "PLD": "REITs",
    "EQIX": "REITs",
    "AMT": "REITs",
    "O": "REITs",
    "SPG": "REITs",
    "PSA": "REITs",
    "DLR": "REITs",
    "WELL": "REITs",

    "RY.TO": "Canada / Banks",
    "TD.TO": "Canada / Banks",
    "BMO.TO": "Canada / Banks",
    "CM.TO": "Canada / Banks",
    "NA.TO": "Canada / Banks",

    "CNQ.TO": "Canada / Energy",
    "SU.TO": "Canada / Energy",
    "CVE.TO": "Canada / Energy",
    "TOU.TO": "Canada / Energy",
    "ARX.TO": "Canada / Energy",

    "AEM.TO": "Canada / Mining",
    "ABX.TO": "Canada / Mining",
    "WPM.TO": "Canada / Mining",
    "FNV.TO": "Canada / Mining",
    "NTR.TO": "Canada / Materials",
    "CCO.TO": "Canada / Uranium",

    "CP.TO": "Canada / Rail",
    "CNR.TO": "Canada / Rail",
    "ATD.TO": "Canada / Consumer Defensive",
    "TFII.TO": "Canada / Transport",
    "WSP.TO": "Canada / Industrials",

    "CSU.TO": "Canada / Tech",
    "DSG.TO": "Canada / Tech",
    "OTEX.TO": "Canada / Tech",
    "KXS.TO": "Canada / Tech",
    "LSPD.TO": "Canada / Tech",

    "BCE.TO": "Canada / Telecom",
    "T.TO": "Canada / Telecom",
    "RCI-B.TO": "Canada / Telecom",

    "DOL.TO": "Canada / Consumer Defensive",
    "EMP-A.TO": "Canada / Consumer Defensive",
    "MRU.TO": "Canada / Consumer Defensive",

    "ENB.TO": "Canada / Pipelines",
    "TRP.TO": "Canada / Pipelines",
    "PPL.TO": "Canada / Pipelines",
    "EMA.TO": "Canada / Utilities",
    "FTS.TO": "Canada / Utilities",

    "SPY": "Market ETF",
    "QQQ": "Market ETF",
    "IWM": "Market ETF",
    "DIA": "Market ETF",
    "SMH": "Sector ETF",
    "SOXX": "Sector ETF",
    "XLF": "Sector ETF",
    "XLV": "Sector ETF",
    "XLE": "Sector ETF",
    "XLI": "Sector ETF",
    "XLY": "Sector ETF",
    "XLP": "Sector ETF",
    "XLU": "Sector ETF",
    "XLB": "Sector ETF",
    "XLRE": "Sector ETF",
}


def get_sector(ticker):
    return SECTOR_MAP.get(ticker, "Other / Uncategorized")